* Error as non-zero in case of an error (Closes: #776216). Thanks to Steve     McIntyre <steve@einval.com> for the bug report and patch.

diff --git a/build-openstack-debian-image b/build-openstack-debian-image
--- a/build-openstack-debian-image
+++ b/build-openstack-debian-image
@@ -192,14 +192,16 @@ else
 fi
 
 cleanup(){
+	error=$?
 	[ ! -d "${MOUNT_DIR}" ] && return
 	echo
-	echo "error, umounting $MOUNT_DIR"
+	echo "error $error, umounting $MOUNT_DIR"
 	chroot ${MOUNT_DIR} umount /proc || true
 	chroot ${MOUNT_DIR} umount /sys || true
 	umount ${MOUNT_DIR}
 	rmdir ${MOUNT_DIR}
 	kpartx -d ${AMI_NAME}
+	exit $error
 }
 trap "cleanup" EXIT TERM INT
 
